name: Build Workflow

run-name: Build Workflow -- ${{github.head_ref || github.ref_name}}

on:
  push:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{github.head_ref || github.ref_name}}

jobs:
  build-job:
    name: Build Job -- ${{github.head_ref || github.ref_name}}
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "Zulu"
          version: "23"

      - name: Build Code
        run: |
          mvn clean install

